name: UnitTests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Testing SDK app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Force XCode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Testing CardKitCore
        run: exec ./.github/scripts/test-card-kit-core.sh
      - name: Install Dependencies
        run: pod install
        shell: bash
      - name: Testing CardKit
        run: exec ./.github/scripts/test-card-kit.sh
      - name: Testing SampleApp
        run: exec ./.github/scripts/test-sample-app-ui.sh